In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Rahul", "Harshita", "Shradha"],
    "CGPA" :[9.5, 7.5, 8.5]
}

df = pd.DataFrame(info)
print(df)

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

In [3]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

In [4]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

#index based access
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1

In [5]:
s = pd.Series([22, 23, 33, 24], index = ["Adam", "Eve", "Bob", "Charlie"])
print(s)
# index based access
print(s[0])
# label based access
print(s["Adam"])
print(s.index)

Adam       22
Eve        23
Bob        33
Charlie    24
dtype: int64
22
22
Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

C:\Users\sneha\AppData\Local\Temp\ipykernel_12420\3854307655.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [6]:
# Properties
# Homogeneous
s = pd.Series([22, 23, 33, 24, "abc"], index = ["Adam", "Eve", "Bob", "Charlie", 23])
print(s)

Adam        22
Eve         23
Bob         33
Charlie     24
23         abc
dtype: object

In [7]:
#Vectrized Operations
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
print(s1 + s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [8]:
# Mutable values, immutable size
s1[0] = 100
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
# DataFrame
info = {
    "Name" : ["Adam", "Rahul", "Ajay", "Yash"],
    "Age" : [22, 23, 20, 22],
    "CGPA" : [8.9, 7.8, 7.5, 9]

    
}
df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

    Name  Age  CGPA
0   Adam   22   8.9
1  Rahul   23   7.8
2   Ajay   20   7.5
3   Yash   22   9.0
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [10]:
df = pd.DataFrame([["Adam", 23], ["Bob", 24], ["Eve", 25]], columns = ["Name", "Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   25

In [11]:
import numpy as np
np_arr = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(np_arr, columns = ["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [12]:
# csv data
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [13]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [14]:
# json data
df = pd.read_json("employee_data.json")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [15]:
 df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [16]:
# Methods
df.head() # starting 5 rows
df.tail(2) # ending 2 rows
df.sample(2)

   ID     Name  Age Department  Salary
2   3  Charlie   28    Finance   48000
0   1    Alice   25         HR   55000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [18]:
df.shape # no. of rows , columns

(10, 5)

In [19]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [20]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [21]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [22]:
# AQI Data Set
df = pd.read_csv("globalAirQuality.csv")
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [23]:
# selecting data
# columns
df["country"]
df[["city", "aqi"]]
# rows
df.loc[0]
df.loc[0:2] # ending index inclusive
df.iloc[2]
df.iloc[0:2]
# cells - rows & columns
df.loc[0, "aqi"]
df.loc[0, ["city", "aqi"]]
df.loc[0:2, ["city", "aqi"]]

df.iloc[0:3, 2]

# cell
df.at[0, "city"]
df.iat[0, 2]

'New York'

In [24]:
# Filtering of data
df[df["aqi"]>100]
df[(df["aqi"]>100) & (df["temperature"] > 30) ]

df[df["aqi"] > 100] [["city", "aqi"]]
aqi_data = df[(df["aqi"]>100) & (df["temperature"] > 30) ] [["city", "aqi"]]
aqi_data
aqi_data.iloc[0]

city    New York
aqi          155
Name: 6, dtype: object

In [25]:
# query returns copy
aqi_val = 100
df.query("aqi > 100")
df.query("aqi > @aqi_val & temperature > 30")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [26]:
# cleaning data
# handle missing values
df = pd.read_csv("raw_data.csv")
df.isnull()
df.isna().sum()
df.dropna() # row drop
df.dropna(axis = 1) #columns
df.fillna(0)
clean_data = df.copy()
clean_data["age"] = clean_data["age"].fillna(df["age"].mean())
df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [28]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [30]:
#handle duplicates
df.duplicated()
df["country"].duplicated()
df2 = df.copy()
df.drop_duplicates(inplace = True)

In [31]:
df = df2

In [32]:
# handle data types
df.dtypes
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64")
df2.dtypes
df["gender"].str.lower()
df["gender"].str.capitalize()
df["name"].str.split(" ")
df["country"].str.contains("india", case = False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [33]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [34]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [35]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [44]:
# Feature Engineering
df2 = df.copy()
df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%")
gender_map = {
    "Male" : "M",
    "Female" : "F",
    "Unknown" : "U"
}
df2["gender"] = df2["gender"].map(gender_map)

df2 = df2.assign(new_income = df2["income"] * 1.1)

df2["country"] = df2["country"].replace("USA", "US")

In [64]:
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]
df2.rename(columns = {"Income": "Salary"})
df2.rename(index = {1: "First"})

df2.sort_values(["Income"])
sorted_df = df2.sort_values(["Income", "Age"])
sorted_df.sort_index()
#reset
sorted_df.reset_index
sorted_df.reset_index(drop = True)

#ranking
# sorted_df["Ranking"] = sorted_df["Income"].rank(ascending = False, method = "dense")
sorted_df[["Id", "Name", "Age", "Country", "Gender", "Income", "New_Income", "Tax"]]
sorted_df

    Id          Name   Age Country Gender   Income  Tax  New_Income
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

In [68]:
df2 = df.copy()
new_col_order = [col for col in df2.columns if col != "id"] + ["id"]
print(new_col_order)
df2[new_col_order]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [73]:
df2 = df.copy()
df2 = df2.drop_duplicates()
df2 = df2.fillna(0)
df2 = df2.sort_values("income")
df2 = df2.reset_index(drop = True)
df2.to_csv("sorted_data.csv")

In [88]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

df.groupby("gender")["income"].mean()
df.groupby("gender")["income"].max()

df.groupby("country")["income"].agg(["mean", "min", "max"])
df.groupby("country")["income"].aggregate(avg_salary = "mean", min_salary = "min", max_salary="max")

df.groupby("country").agg({
    "income" : "mean",
    "age" : "mean"
})

df.groupby("country").agg({
    "income" : "max",
    "age" : "min"
})
df.groupby("country").agg(
    max_salary = ("income" , "max"),
    avg_age = ("age" , "mean")
)

         max_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5